name: rapids-26.02
channels:
  - defaults
dependencies:
  - rapids=26.02
  - cuda-version[version='>=13.0,<=13.1']
  - python=3.10
  - _libgcc_mutex=0.1
  - attr=2.5.1
  - aws-c-auth=0.9.0
  - aws-c-common=0.12.3
  - aws-c-event-stream=0.5.4
  - azure-core-cpp=1.14.0
  - bokeh=3.7.3
  - brotli-python=1.1.0
  - c-ares=1.34.5
  - ca-certificates=2026.2.25
  - cachetools=6.1.0
  - cffi=1.17.1
  - click=8.2.1
  - cloudpickle=3.1.1
  - cytoolz=1.0.1
  - fastrlock=0.8.3
  - fmt=11.0.2
  - fsspec=2025.5.1
  - h2=4.2.0
  - importlib-metadata=8.7.0
  - joblib=1.5.1
  - keyutils=1.6.1
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20250127.1
  - libarrow=19.0.1
  - libblas=3.9.0
  - libcap=2.75
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcrypt-lib=1.11.1
  - libgpg-error=1.55
  - libjpeg-turbo=3.1.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.49
  - libsqlite=3.50.2
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvmlite=0.43.0
  - lz4=4.4.4
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - msgpack-python=1.1.1
  - narwhals=1.44.0
  - openssl=3.6.1
  - orc=2.1.2
  - packaging=25.0
  - pandas=2.2.3
  - pillow=11.2.1
  - pip=25.1.1
  - psutil=7.0.0
  - pynvml=12.0.0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyyaml=6.0.2
  - readline=8.2
  - rich=14.0.0
  - setuptools=80.9.0
  - snappy=1.2.1
  - spdlog=1.14.1
  - tblib=3.1.0
  - toolz=1.0.0
  - tornado=6.5.1
  - typing_extensions=4.14.0
  - tzdata=2025b
  - wheel=0.45.1
  - xyzservices=2025.4.0
  - zstandard=0.23.0
